### ISSUE TITLE
Introduction text gets cutt of on iPhone 7

### ISSUE THREAD

**Issue by sandersantema** [Flaque/quirk#30] opened 2019-01-04 10:37 UTC
The introduction gets cut off on iPhone 7

![img_0036](https://user-images.githubusercontent.com/21057514/50684237-02de6e00-1015-11e9-9889-c500e5f59c34.PNG)

**Comment by Flaque** [comment] 2019-01-04 15:48
Hmm, I’ll fix this.

**Comment by Flaque** [comment] 2019-02-11 02:53
^ As far as I know this has been fixed. If someone finds an example of where this is still happening let me know

**Comment by OolonColoophid** [comment] 2019-04-06 17:04
Hi Flaque

Great app - I can see it would be really useful (I'm a cognitive psychologist with a passing acquaintance with CBT). 

Unfortunately, this is still happening - however, if you believe you've fixed it, it might be caused by the larger text in Settings/Accessibility. My iPhone settings are below:

![IMG_8310](https://user-images.githubusercontent.com/18744451/55672729-52dc0380-5896-11e9-9d49-652b264ca3f9.PNG)

![IMG_8311](https://user-images.githubusercontent.com/18744451/55672734-5b343e80-5896-11e9-8d73-c786f5fb34fa.PNG)

Cheers

Ian

**Comment by Flaque** [comment] 2019-04-07 05:08
@OolonColoophid, ah good catch.

**Comment by nmatt** [comment] 2019-04-07 18:40
I see the same problem on iPhone SE, see the screenshot below. I have dynamic text size set to one tick above the middle position.

![quirk](https://user-images.githubusercontent.com/7593340/55688091-1206ec00-5975-11e9-9f91-e8d4d1a94781.png)

**Comment by Flaque** [comment] 2019-04-08 23:01
Closing in favor of #63 since I think that's the solution to this.

**Closed by Flaque** 2019-04-08 23:01 UTC
Labels: bug
