### ISSUE TITLE
Text getting cut off on Android One plus 6T

### ISSUE THREAD

**Issue by jonshern** [Flaque/quirk#128] opened 2019-06-15 03:51 UTC
Many of the screens have one letter or cut off on the right
I noticed on the Galaxy s9 all of the characters were present
On the oneplus 6t.  Several characters get cut off
Examples 
K in the quirk title
E on the save button

![Screenshot_20190614-224824](https://user-images.githubusercontent.com/1264760/59546620-8ff7ee00-8ef6-11e9-9bcf-54b231107f7e.jpg)

**Comment by jonshern** [comment] 2019-06-15 03:55
Resolution comparison

The Samsung S9 has the smaller screen at 5.8 inches, but its AMOLED display comes in high-resolution Quad HD+ (2960x1440), which reaches an impressive 570 ppi pixel density.

The OnePlus 6T has a bigger 6.41-inch 19.5:9 AMOLED display, though its 2340x1080 resolution manages only 402 ppi.

**Comment by Flaque** [comment] 2019-06-15 04:29
Huh, this is REALLY weird. Not the typical "stuff gets cut off" bug either. hmmm... I'll take a look.

**Comment by jonshern** [comment] 2019-06-15 15:18
I did some research and found this issue in react native
https://github.com/facebook/react-native/issues/15114

I tried changing my font from their default of OnePlus Slate to Roboto and everything looks good

**Comment by FutureProg** [comment] 2019-07-13 02:13
@jonshern This relates to [my issue from May](https://github.com/Flaque/quirk/issues/117#issuecomment-511020102). I don't believe that a work around should mean that the issue should be closed, even if it is an issue with react native. On the user side, I'd rather have the OnePlus native font over Roboto (I chose it for a reason) and wouldn't want to change everything just so I can easily use one app.

**Comment by Flaque** [comment] 2019-07-27 17:56
Hmm, maybe we could just put `OnePlus native font` in the fontstack?

**Comment by Flaque** [comment] 2019-08-10 19:41
Ahhhh I hate stalebot I need to kill it

**Comment by FutureProg** [comment] 2019-08-10 21:50
:o bots have rights. I've been meaning to at least try and fix this for so long. Might take a look in a couple hours.

**Comment by Flaque** [comment] 2019-08-10 21:52
:o Thank you! I don't have an Android One Plus :( So this has been a bit on hold on our end.

**Comment by FutureProg** [comment] 2019-08-11 20:43
@Flaque Looks like you added the fix this morning, I'm having trouble running this locally but it seems to be fine in production right now 🤔 You can probably close this issue then. 😄

**Comment by Flaque** [comment] 2019-08-11 20:49
Hurray! I didn't want to close it until someone confirmed it. 😅

**Closed by Flaque** 2019-08-11 20:49 UTC
Labels: bug
