### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by qazip** [Flaque/quirk#54] opened 2019-04-07 11:06 UTC
I hate writing in portraid mode, I can't in fact! It would be nice if quirk supported landscape mode.

**Comment by idnovic** [comment] 2019-04-07 16:39
Duplicate of #48

**Comment by Flaque** [comment] 2019-04-07 16:58
> I can't in fact

@qazip --> What do you mean by you _can't_. Is this an accessibility issue?

**Comment by qazip** [comment] 2019-04-07 17:01
> > I can't in fact
> 
> @qazip --> What do you mean by you _can't_. Is this an accessibility issue?

Oh no, fortunately not that. I guess my wording was imprecise. I just can't type fast without making several typos. Screen is (relatively) small for writing in portrait mode..

**Comment by idnovic** [comment] 2019-04-07 18:53
screen rotation pull request https://github.com/Flaque/quirk/pull/61

**Closed** 2019-07-19 20:19 UTC
Labels: wontfix
